import numpy as np
import pandas as pd
import numpy as np
import os
import h5py
import scipy.io

def read_index_map(dir_name: str, open_type = 'h5py') -> np.ndarray:
    """ReadCellReg: Read the MATLAB file saved by CellReg.
    CellReg: https://doi.org/10.1016/j.celrep.2017.10.013

    Parameters
    ----------
    dir_name : str
        The directory of the MATLAB file
    open_type : str, optional
        The method to open the MATLAB file, depending on the file signature
        Generally, 'h5py' and 'scipy' are used, by default 'h5py'
        'h5py' is needed when using v7.3 signature to save the file
        'scipy' is needed when 'h5py' does not work, relating to old-version MATLAB file.

    Returns
    -------
    index_map, numpy.ndarray with 2 dimensions (n_sessions, n_neurons)
        The index_map of neuron IDs.
        
    Raises
    ------
    FileNotFoundError
        If the directory does not exist
    """
    if os.path.exists(dir_name) == False:
        raise FileNotFoundError
    
    if open_type == 'h5py':
        with h5py.File(dir_name, 'r') as f:
            cell_registered_struct = f['cell_registered_struct']
            index_map = np.array(cell_registered_struct['cell_to_index_map'])
        return index_map.astype(np.int64)

    elif open_type == 'scipy':
        f = scipy.io.loadmat(dir_name)
        cell_registered_struct = f['cell_registered_struct']
        index_map = np.array(cell_registered_struct['cell_to_index_map'])
        return index_map.astype(np.int64)
    
def read_footprint(dir_name: str, open_type = 'h5py', key_word: str = 'SFP') -> np.ndarray:
    """read_footprint: Read the spatial footprint generated by
    CNMF-E (https://doi.org/10.7554/eLife.28728)
    or suit2P (https://doi.org/10.1101/061507).

    Parameters
    ----------
    dir_name : str
        The directory of the footprint
    open_type : str, optional
        The method to open the MATLAB file, depending on the file signature
        Generally, 'h5py' and 'scipy' are used, by default 'h5py'
        'h5py' is needed when using v7.3 signature to save the file
        'scipy' is needed when 'h5py' does not work, relating to old-version MATLAB file.
    key_word : str, optional
        key work to reach the footprint matrix, by default 'SFP'

    Returns
    -------
    np.ndarray
        The footprint matrix, three dimensions (n_neurons, n_pixels width, n_pixels height)

    Raises
    ------
    FileNotFoundError
        If the directory does not exist
    """
    if os.path.exists(dir_name) == False:
        raise FileNotFoundError
    
    if open_type == 'h5py':
        with h5py.File(dir_name, 'r') as f:
            sfp = np.array(f['SFP'])
        return sfp
    elif open_type == 'scipy':
        f = scipy.io.loadmat(dir_name)
        sfp = np.array(f['SFP'])
        return sfp